<template>
  <v-list>
    <v-list-tile>
      <v-list-tile-content>
        <v-list-tile-title>ID</v-list-tile-title>
        <v-list-tile-sub-title>{{this.container.Id}}</v-list-tile-sub-title>
      </v-list-tile-content>
    </v-list-tile>
    <v-list-tile>
      <v-list-tile-content>
        <v-list-tile-title>Created</v-list-tile-title>
        <v-list-tile-sub-title>{{this.container.Created}}</v-list-tile-sub-title>
      </v-list-tile-content>
    </v-list-tile>
    <v-list-tile>
      <v-list-tile-content>
        <v-list-tile-title>Command</v-list-tile-title>
        <v-list-tile-sub-title>{{this.container.Command}}</v-list-tile-sub-title>
      </v-list-tile-content>
    </v-list-tile>
    <v-list-tile>
      <v-list-tile-content>
        <v-list-tile-title>Image</v-list-tile-title>
        <v-list-tile-sub-title>{{this.container.Image}}</v-list-tile-sub-title>
      </v-list-tile-content>
    </v-list-tile>
    <v-list-tile>
      <v-list-tile-content>
        <v-list-tile-title>State</v-list-tile-title>
        <v-list-tile-sub-title>{{this.container.State}}</v-list-tile-sub-title>
      </v-list-tile-content>
    </v-list-tile>
    <v-list-tile>
      <v-list-tile-content>
        <v-list-tile-title>Status</v-list-tile-title>
        <v-list-tile-sub-title>{{this.container.Status}}</v-list-tile-sub-title>
      </v-list-tile-content>
    </v-list-tile>
  </v-list>
</template>

<script>
export default {
  props: ["container"]
};
</script>

<style>
</style>
